config/routes.rb
Rails.application.routes.draw do
  resources :asign_team_user_categories
  resources :teams
  resources :categories
  resources :asign_departament_users
  resources :departaments
  resources :corporations
  resources :companies
  devise_for :users
  resources :usersss
  resources :roles
  resources :users_roles
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :asginar_tickets
  resources :ticket_detalles
  resources :ticket_files
  resources :tickets
  resources :categorias
  resources :asignacion_equipos
  resources :equipos
  resources :categoria
  resources :asignar_departamento_usuarios
  resources :departamentos
  resources :empresas
  resources :companias
  resources :corporacions





# root to: "home#index"

devise_scope :user do
    get 'signout', to: 'devise/sessions#destroy', as: :signout
    get 'sign_in', to: 'users/sessions#new', as: :sign_in
  end


  get 'tomar' => 'asginar_tickets#tomar'
  get 'cerrar' => 'tickets#cerrar'
  # defaults to dashboard
  root :to => redirect('/dashboard/dashboard')

  # view routes
  get '/widgets' => 'widgets#index'
  get '/documentation' => 'documentation#index'

  get 'dashboard/dashboard_v1'
  get 'dashboard/dashboard_v2'
  get 'dashboard/dashboard_v3'
  get 'dashboard/dashboard_h'
  get 'dashboard/dashboard'
  get 'dashboard/soporte'
  get 'tickets/new_su'
  get 'elements/button'
  get 'elements/notification'
  get 'elements/spinner'
  get 'elements/animation'
  get 'elements/dropdown'
  get 'elements/nestable'
  get 'elements/sortable'
  get 'elements/panel'
  get 'elements/portlet'
  get 'elements/grid'
  get 'elements/gridmasonry'
  get 'elements/typography'
  get 'elements/fonticons'
  get 'elements/weathericons'
  get 'elements/colors'
  get 'elements/buttons'
  get 'elements/notifications'
  get 'elements/carousel'
  get 'elements/tour'
  get 'elements/sweetalert'
  get 'forms/standard'
  get 'forms/extended'
  get 'forms/validation'
  get 'forms/wizard'
  get 'forms/upload'
  get 'forms/xeditable'
  get 'forms/imgcrop'
  get 'multilevel/level1'
  get 'multilevel/level3'
  get 'charts/flot'
  get 'charts/radial'
  get 'charts/chartjs'
  get 'charts/chartist'
  get 'charts/morris'
  get 'charts/rickshaw'
  get 'tables/standard'
  get 'tables/extended'
  get 'tables/datatable'
  get 'tables/jqgrid'
  get 'maps/google'
  get 'maps/vector'
  get 'extras/mailbox'
  get 'extras/timeline'
  get 'extras/calendar'
  get 'extras/invoice'
  get 'extras/search'
  get 'extras/todo'
  get 'extras/profile'
  get 'extras/contacts'
  get 'extras/contact_details'
  get 'extras/projects'
  get 'extras/project_details'
  get 'extras/team_viewer'
  get 'extras/social_board'
  get 'extras/vote_links'
  get 'extras/bug_tracker'
  get 'extras/faq'
  get 'extras/help_center'
  get 'extras/followers'
  get 'extras/settings'
  get 'extras/plans'
  get 'extras/file_manager'
  get 'blog/blog'
  get 'blog/blog_post'
  get 'blog/blog_articles'
  get 'blog/blog_article_view'
  get 'ecommerce/ecommerce_orders'
  get 'ecommerce/ecommerce_order_view'
  get 'ecommerce/ecommerce_products'
  get 'ecommerce/ecommerce_product_view'
  get 'ecommerce/ecommerce_checkout'
  get 'forum/forum_categories'
  get 'forum/forum_topics'
  get 'forum/forum_discussion'
  get 'pages/login'
  get 'pages/register'
  get 'pages/recover'
  get 'pages/lock'
  get 'pages/template'
  get 'pages/notfound'
  get 'pages/maintenance'
  get 'pages/error500'

  # api routes
  get '/api/documentation' => 'api#documentation'
  get '/api/datatable' => 'api#datatable'
  get '/api/jqgrid' => 'api#jqgrid'
  get '/api/jqgridtree' => 'api#jqgridtree'
  get '/api/i18n/:locale' => 'api#i18n'
  post '/api/xeditable' => 'api#xeditable'
  get '/api/xeditable-groups' => 'api#xeditablegroups'

  # the rest goes to root
  get '*path' => redirect('/')
end

app/models/ticket_file.rb
class TicketFile < ApplicationRecord

  belongs_to :user
  belongs_to :ticket
  
end

app/controllers/ticket_files_controller.rb
class TicketFilesController < ApplicationController
  before_action :set_ticket_file, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!
  before_action :admin_required

  # GET /ticket_files
  # GET /ticket_files.json
  def index
    @ticket_files = TicketFile.all
  end

  # GET /ticket_files/1
  # GET /ticket_files/1.json
  def show
  end

  # GET /ticket_files/new
  def new
    @ticket_file = TicketFile.new
  end

  # GET /ticket_files/1/edit
  def edit
  end

  # POST /ticket_files
  # POST /ticket_files.json
  def create
    @ticket_file = TicketFile.new(ticket_file_params)

    respond_to do |format|
      if @ticket_file.save
        format.html { redirect_to @ticket_file, notice: 'Ticket file was successfully created.' }
        format.json { render :show, status: :created, location: @ticket_file }
      else
        format.html { render :new }
        format.json { render json: @ticket_file.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /ticket_files/1
  # PATCH/PUT /ticket_files/1.json
  def update
    respond_to do |format|
      if @ticket_file.update(ticket_file_params)
        format.html { redirect_to @ticket_file, notice: 'Ticket file was successfully updated.' }
        format.json { render :show, status: :ok, location: @ticket_file }
      else
        format.html { render :edit }
        format.json { render json: @ticket_file.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /ticket_files/1
  # DELETE /ticket_files/1.json
  def destroy
    @ticket_file.destroy
    respond_to do |format|
      format.html { redirect_to ticket_files_url, notice: 'Ticket file was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_ticket_file
      @ticket_file = TicketFile.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def ticket_file_params
      params.require(:ticket_file).permit(:ticket_id, :user_id, :mensaje)
    end
end

app/views/ticket_files/_form.html.erb
<%= form_with(model: ticket_file, local: true) do |form| %>
  <% if ticket_file.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(ticket_file.errors.count, "error") %> prohibited this ticket_file from being saved:</h2>

      <ul>
      <% ticket_file.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :ticket_id %>
    <%= form.text_field :ticket_id, id: :ticket_file_ticket_id %>
  </div>

  <div class="field">
    <%= form.label :user_id %>
    <%= form.text_field :user_id, id: :ticket_file_user_id %>
  </div>

  <div class="field">
    <%= form.label :mensaje %>
    <%= form.text_area :mensaje, id: :ticket_file_mensaje %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/ticket_files/edit.html.erb
<h1>Editing Ticket File</h1>

<%= render 'form', ticket_file: @ticket_file %>

<%= link_to 'Show', @ticket_file %> |
<%= link_to 'Back', ticket_files_path %>

app/views/ticket_files/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Ticket Files</h1>

<table>
  <thead>
    <tr>
      <th>Ticket</th>
      <th>User</th>
      <th>Mensaje</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @ticket_files.each do |ticket_file| %>
      <tr>
        <td><%= ticket_file.ticket_id %></td>
        <td><%= ticket_file.user_id %></td>
        <td><%= ticket_file.mensaje %></td>
        <td><%= link_to 'Show', ticket_file %></td>
        <td><%= link_to 'Edit', edit_ticket_file_path(ticket_file) %></td>
        <td><%= link_to 'Destroy', ticket_file, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Ticket File', new_ticket_file_path %>

app/views/ticket_files/new.html.erb
<h1>New Ticket File</h1>

<%= render 'form', ticket_file: @ticket_file %>

<%= link_to 'Back', ticket_files_path %>

app/views/ticket_files/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Ticket:</strong>
  <%= @ticket_file.ticket_id %>
</p>

<p>
  <strong>User:</strong>
  <%= @ticket_file.user_id %>
</p>

<p>
  <strong>Mensaje:</strong>
  <%= @ticket_file.mensaje %>
</p>

<%= link_to 'Edit', edit_ticket_file_path(@ticket_file) %> |
<%= link_to 'Back', ticket_files_path %>